### ISSUE TITLE
For what Sitecore version is the csv

### ISSUE THREAD

**Issue by sebastiantecsi** [AlenPelin/Sitecore-Configurator#1]
Hello Alen,

http://dl.sitecore.net/updater/info/static/config.csv for what Sitecore version specifically is this one ? 
I need the one for Sitecore 8.1 update 3.
And here Config Enable Disable Excel spreadsheet (  https://doc.sitecore.net//~/media/26CC1C22808645D09D867568D3D8EF4F.ashx?la=en ) is only for Sitecore 8.2 . I found the link in couple of pages eq: https://doc.sitecore.net/sitecore_experience_platform/setting_up__maintaining/xdb/configuring_servers/configure_a_content_delivery_server

Also in your config.csv for SwitchMasterToWeb.config.example on Content Delivery CD it should be enabled, as right now is marked as n/a

Thank you,
Sebastian

**Comment by AlenPelin** [comment]
Thanks @sebastiantecsi for attention to the project and for your remarks. My csv was made from latest 8.1 excel file a month or two ago. It could have been changed since then, I will take a look, thanks.

You can get different versions of the file on the mentioned [Configure Content Delivery Server](https://doc.sitecore.net/sitecore_experience_platform/setting_up__maintaining/xdb/configuring_servers/configure_a_content_delivery_server) page by changing version from the dropdown on the right hand side in the top of the page.

**Comment by sebastiantecsi** [comment]
Thank you Allen for the answer.
